addons:
  apt:
    packages:
    - python-tables
install:
  - pip install --upgrade pip  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -r requirements.txt
language: python
python: "2.7"
script: make test-ci
sudo: false
virtualenv:
  system_site_packages: true
